### PR TITLE
Support for attachments

### PR DESCRIPTION
**Pull request by obaid**
- Added support for handling incoming notifications that aren't messages
- Added support for handling incoming attachments

### CODE REVIEW

**Comment by CasperLaiTW** [comment]
Thank you for your PR.
I found the ReceiveMessage __construct parameters so complicated. (#28)
And I am already start refactor it.
Next release will change construct params.

**Comment by obaid** [comment]
@CasperLaiTW thanks for accepting the PR.

Do you have a roadmap document that we can share? I am actively developing an application using this library so it would be great to know what changes are upcoming.

**Comment by CasperLaiTW** [comment]
@obaid. First, thanks for you using the library on your project
I am sorry. The project is maintained on my free time, so I didn't plan any roadmap or schedule.
But next release do not update any getter function or interface, so do not worry about compatibility.

**Comment by CasperLaiTW** [comment]
I check facebook messenger platform changelog, they are release new version.
Maybe I can plan some feature and create milestone on github.
Hope to help for you.

The v1.1 is almost done, maybe into plan v1.2

If you have any feature or enhancement idea, please create issue to me.
I will use my free time to implement.

**Comment by obaid** [comment]
I completely understand that. Perhaps, I will continue to add features / bug fixes as I go with my development effort and I will keep submitting PR requests to merge them in.

**Pull request merged**
